// Comprehensive Browser Dataset (10 Major Web Browsers)
const browsersData = [
    {
        id: 'chrome',
        name: 'Google Chrome',
        tagline: 'The world\'s most popular web browser',
        category: 'chromium',
        engine: 'Blink',
        speed: 95,
        ramUsage: 'High (~1.5GB+)',
        privacy: 'Moderate',
        extensions: 'Extensive (Chrome Web Store)',
        sync: 'Excellent (Google Account)',
        vpn: 'No (Extension required)',
        adblocker: 'No (Manifest v3 limits)',
        openSource: 'No (Chromium open, Chrome proprietary)',
        customization: 'Moderate',
        tabManagement: 'Good (Tab Groups, Search Tabs)',
        aiIntegration: 'Gemini AI built-in',
        platforms: ['Windows', 'Mac', 'Linux', 'Android', 'iOS'],
        downloadUrl: 'https://www.google.com/chrome/',
        icon: 'fa-brands fa-chrome',
        color: 'from-red-500 to-yellow-500',
        badgeBg: 'bg-red-500/10 text-red-400 border-red-500/20',
        pros: ['Massive extension ecosystem', 'Seamless Google Sync', 'Fast JavaScript performance'],
        cons: ['High RAM consumption', 'Aggressive telemetry / data tracking']
    },
    {
        id: 'firefox',
        name: 'Mozilla Firefox',
        tagline: 'Fast, private & fiercely independent',
        category: 'gecko',
        engine: 'Gecko',
        speed: 90,
        ramUsage: 'Moderate (~800MB)',
        privacy: 'High',
        extensions: 'Great (Add-ons ecosystem + Mobile support)',
        sync: 'Excellent (Firefox Account)',
        vpn: 'Optional (Mozilla VPN paid)',
        adblocker: 'Yes (uBlock Origin full support)',
        openSource: 'Yes (100% Open Source)',
        customization: 'High (CSS / about:config)',
        tabManagement: 'Good (Vertical tabs via addons)',
        aiIntegration: 'Experimental / Extension based',
        platforms: ['Windows', 'Mac', 'Linux', 'Android', 'iOS'],
        downloadUrl: 'https://www.mozilla.org/firefox/',
        icon: 'fa-brands fa-firefox-browser',
        color: 'from-orange-500 to-amber-600',
        badgeBg: 'bg-orange-500/10 text-orange-400 border-orange-500/20',
        pros: ['Independent Gecko engine (non-Chromium)', 'Superior uBlock Origin support', 'Strong privacy stance'],
        cons: ['Lower market share', 'Some niche site rendering edge cases']
    },
    {
        id: 'safari',
        name: 'Apple Safari',
        tagline: 'Optimized for energy efficiency on Apple devices',
        category: 'webkit',
        engine: 'WebKit',
        speed: 96,
        ramUsage: 'Low (~400MB)',
        privacy: 'Very High',
        extensions: 'Good (Mac App Store)',
        sync: 'Excellent (iCloud Keychain)',
        vpn: 'Yes (iCloud Private Relay)',
        adblocker: 'Yes (Safari Extensions)',
        openSource: 'No (WebKit engine open, Safari proprietary)',
        customization: 'Low',
        tabManagement: 'Great (Tab Groups, pinned tabs)',
        aiIntegration: 'Apple Intelligence integrated',
        platforms: ['Mac', 'iOS'],
        downloadUrl: 'https://www.apple.com/safari/',
        icon: 'fa-brands fa-safari',
        color: 'from-blue-400 to-cyan-500',
        badgeBg: 'bg-blue-400/10 text-blue-400 border-blue-400/20',
        pros: ['Unmatched battery life on Mac/iPhone', 'Intelligent Tracking Prevention', 'Deep Apple ecosystem integration'],
        cons: ['Exclusive to Apple hardware', 'Slower extension adoption']
    },
    {
        id: 'edge',
        name: 'Microsoft Edge',
        tagline: 'AI-powered browsing with Copilot integration',
        category: 'chromium',
        engine: 'Blink',
        speed: 95,
        ramUsage: 'Moderate (Efficiency mode)',
        privacy: 'Moderate',
        extensions: 'Extensive (Chrome & Edge stores)',
        sync: 'Excellent (Microsoft Account)',
        vpn: 'Yes (Built-in free 5GB/mo VPN)',
        adblocker: 'No (AdGuard / uBlock required)',
        openSource: 'No',
        customization: 'High (Collections, Sidebar apps)',
        tabManagement: 'Excellent (Vertical Tabs, Sleeping Tabs)',
        aiIntegration: 'Microsoft Copilot built-in',
        platforms: ['Windows', 'Mac', 'Linux', 'Android', 'iOS'],
        downloadUrl: 'https://www.microsoft.com/edge',
        icon: 'fa-brands fa-edge',
        color: 'from-blue-600 to-teal-500',
        badgeBg: 'bg-teal-500/10 text-teal-400 border-teal-500/20',
        pros: ['Built-in Copilot AI sidebar', 'Sleeping Tabs save RAM', 'Vertical tabs layout native'],
        cons: ['Aggressive Windows promotion', 'Bloated with Microsoft services']
    },
    {
        id: 'brave',
        name: 'Brave Browser',
        tagline: 'Shields up for blazing speed and privacy',
        category: 'privacy',
        engine: 'Blink',
        speed: 97,
        ramUsage: 'Low-Moderate (~600MB)',
        privacy: 'Very High',
        extensions: 'Extensive (Chrome Web Store)',
        sync: 'Good (Encrypted sync chain)',
        vpn: 'Yes (Brave Firewall + VPN paid)',
        adblocker: 'Yes (Native built-in Brave Shields)',
        openSource: 'Yes (Open Source)',
        customization: 'High',
        tabManagement: 'Good (Vertical tabs, tab search)',
        aiIntegration: 'Leo AI Assistant built-in',
        platforms: ['Windows', 'Mac', 'Linux', 'Android', 'iOS'],
        downloadUrl: 'https://brave.com/',
        icon: 'fa-solid fa-shield-halved',
        color: 'from-orange-600 to-red-600',
        badgeBg: 'bg-orange-600/10 text-orange-400 border-orange-600/20',
        pros: ['Blocks trackers & ads out of the box', 'Built-in Leo AI', 'Faster page loads by stripping scripts'],
        cons: ['Crypto/rewards features can feel intrusive', 'Chromium monopoly dependency']
    },
    {
        id: 'opera',
        name: 'Opera GX / Opera One',
        tagline: 'Gamer browser with CPU/RAM limiters & AI',
        category: 'chromium',
        engine: 'Blink',
        speed: 92,
        ramUsage: 'Customizable (GX Limiters)',
        privacy: 'Moderate',
        extensions: 'Extensive (Chrome Store)',
        sync: 'Good (Opera Flow)',
        vpn: 'Yes (Built-in free unlimited VPN)',
        adblocker: 'Yes (Built-in adblock)',
        openSource: 'No',
        customization: 'Extreme (RGB themes, sound effects)',
        tabManagement: 'Great (Island tabs, workspaces)',
        aiIntegration: 'Aria AI built-in',
        platforms: ['Windows', 'Mac', 'Linux', 'Android', 'iOS'],
        downloadUrl: 'https://www.opera.com/',
        icon: 'fa-solid fa-o',
        color: 'from-red-600 to-rose-700',
        badgeBg: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
        pros: ['RAM and CPU hardware limiters', 'Free built-in VPN', 'Tab Islands & Workspaces'],
        cons: ['Data collection concerns (Chinese consortium ownership)', 'Can feel heavy / flashy']
    },
    {
        id: 'arc',
        name: 'Arc Browser',
        tagline: 'The internet computer for your modern workflow',
        category: 'webkit',
        engine: 'Flow/Blink',
        speed: 94,
        ramUsage: 'Moderate',
        privacy: 'High',
        extensions: 'Extensive (Chrome Store)',
        sync: 'Good (Arc Account)',
        vpn: 'No',
        adblocker: 'No (Extension required)',
        openSource: 'No',
        customization: 'Extreme (Spaces, Split view, Themes)',
        tabManagement: 'Revolutionary (Sidebar, Spaces, Profiles)',
        aiIntegration: 'Arc Max AI (Pinch to peek, 5-sec summaries)',
        platforms: ['Mac', 'Windows', 'iOS'],
        downloadUrl: 'https://arc.net/',
        icon: 'fa-solid fa-bolt-lightning',
        color: 'from-purple-600 to-pink-600',
        badgeBg: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
        pros: ['Revolutionary vertical sidebar & spaces', 'Split view in single tab', 'Arc Max AI productivity features'],
        cons: ['Requires learning new paradigm', 'Windows version still maturing']
    },
    {
        id: 'tor',
        name: 'Tor Browser',
        tagline: 'Anonymity online with onion routing',
        category: 'privacy',
        engine: 'Tor/Gecko',
        speed: 70,
        ramUsage: 'Moderate',
        privacy: 'Maximum',
        extensions: 'Limited (Strictly restricted for security)',
        sync: 'None (Deliberate)',
        vpn: 'Yes (Tor Onion Network routing)',
        adblocker: 'Yes (NoScript built-in)',
        openSource: 'Yes (100% Open Source)',
        customization: 'Low (Security slider)',
        tabManagement: 'Basic',
        aiIntegration: 'None',
        platforms: ['Windows', 'Mac', 'Linux', 'Android'],
        downloadUrl: 'https://www.torproject.org/',
        icon: 'fa-solid fa-user-secret',
        color: 'from-purple-800 to-indigo-900',
        badgeBg: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
        pros: ['Absolute anonymity via onion routing', 'Defeats ISP surveillance & fingerprinting', 'Open source gold standard'],
        cons: ['Very slow page loading speeds', 'Breaks interactive JavaScript sites']
    },
    {
        id: 'vivaldi',
        name: 'Vivaldi',
        tagline: 'Extremely customizable browser for power users',
        category: 'chromium',
        engine: 'Blink',
        speed: 93,
        ramUsage: 'Moderate',
        privacy: 'High',
        extensions: 'Extensive (Chrome Store)',
        sync: 'Good (End-to-end encrypted sync)',
        vpn: 'No',
        adblocker: 'Yes (Built-in ad & tracker blocker)',
        openSource: 'Partial (UI proprietary, backend open)',
        customization: 'Maximum (Custom shortcuts, UI layouts)',
        tabManagement: 'Best in Class (Tab stacking, tiling)',
        aiIntegration: 'Vivaldi Mail / Notes integrated',
        platforms: ['Windows', 'Mac', 'Linux', 'Android'],
        downloadUrl: 'https://vivaldi.com/',
        icon: 'fa-solid fa-v',
        color: 'from-red-700 to-orange-600',
        badgeBg: 'bg-red-600/10 text-red-400 border-red-600/20',
        pros: ['Unrivaled UI customization & tab stacking', 'Built-in Mail, Calendar & Notes', 'No user profiling'],
        cons: ['Steep learning curve for casual users', 'Slightly complex settings menu']
    },
    {
        id: 'duckduckgo',
        name: 'DuckDuckGo',
        tagline: 'Privacy, simplified for mobile and desktop',
        category: 'privacy',
        engine: 'Blink/WebKit',
        speed: 95,
        ramUsage: 'Low',
        privacy: 'Very High',
        extensions: 'Limited',
        sync: 'Good (Encrypted QR sync)',
        vpn: 'Yes (Subscription privacy protection)',
        adblocker: 'Yes (Email protection, tracker blocker)',
        openSource: 'Partial',
        customization: 'Low',
        tabManagement: 'Basic (Fire button clears data)',
        aiIntegration: 'DuckAssist AI',
        platforms: ['Windows', 'Mac', 'Android', 'iOS'],
        downloadUrl: 'https://duckduckgo.com/browser',
        icon: 'fa-solid fa-shield-cat',
        color: 'from-amber-500 to-orange-500',
        badgeBg: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
        pros: ['Instant "Fire Button" wipes data instantly', 'App Tracking Protection on mobile', 'Clean uncluttered experience'],
        cons: ['Fewer extensions than desktop giants', 'Not as feature-rich for power users']
    }
];
